# Terraform Variables
# Generated by setup wizard


# SSH access for your IP (configured via setup wizard)
additional_ssh_ips = ["163.116.245.87/32"]


# Cloudflare Configuration (configured via setup wizard)
# Note: CLOUDFLARE_API_TOKEN is in GitHub Secrets, not this file


